const Map<String, Map<String, String>> languageData = {
  'en': {
    'Alen': 'Alen',
    'Language': 'Language',
    'Services': 'Services',
    'Pharmacies': 'Pharmacies',
    'Imaging': 'Imaging',
    'Labs': 'Labs',
    'HomeCare': 'Home Care',
    'Health Facilities': 'Health Facilities',
    'Importers': 'Importers',
    'Companies': 'Companies',
    'EmergencyMS': 'Emergency',
    'Trending': 'Trending',
    'Health Articles': 'Health Articles',
    'Search': 'Search',
    'Top Pharmacies': 'Top Pharmacies',
    'Nearby Pharmacies': 'Nearby Pharmacies',
    'Top Diagnostics': 'Top Diagnostics',
    'Nearby Diagnostics': 'Nearby Diagnostics',
    'Top Laboratories': 'Top Laboratories',
    'Nearby Laboratories': 'Nearby Laboratories',
    'Top Home Cares': 'Top Home Cares',
    'Nearby Home Cares': 'Nearby Home Cares',
    'Top Hospitals': 'Top Hospitals',
    'Nearby Hospitals': 'Nearby Hospitals',
    'Top Importers': 'Top Importers',
    'Nearby Importers': 'Nearby Importers',
    'Top Companies': 'Top Companies',
    'Nearby Companies': 'Nearby Companies',
    'Categories': 'Categories',
    'Office Hours': 'Office Hours',
    'Phone Number': 'Phone Number',
    'Email': 'Email',
    'Our Location': 'Our Location',
    'Add to Cart': 'Add to Cart',
    'Dosage': 'Dosage',
    'Made-in': 'Made-in',
    'Quantity': 'Quantity',
    'Root': 'Root',
    'Price': 'Price',
    'Yes': 'Yes',
    'No': 'No',
    'Catalogues': 'Catalogues',
    'Sub-catalogue': 'Sub-catalogue',
    'Types': 'Types',
    'Search Everything': 'Search Everything',
    'Confirmation Code is required!': 'Confirmation Code is required!',
    'Please provide your Confirmation Code':
        'Please provide your Confirmation Code',
    'Please provide your complete Confirmation Code':
        'Please provide your complete Confirmation Code',
    'Incorrect give a valid Confirmation Code':
        'Incorrect give a valid Confirmation Code',
    'Confirmation Code': 'Confirmation Code',
    'Sign up': 'Sign Up',
    'Additional Info': 'Additional Info',
    'First name is required!': 'First name is required!',
    'Incorrect Email Address': 'Incorrect Email Address',
    'Age is required!': 'Age is required!',
    'Please provide you age': 'Please provide you age',
    'Age must be a number': 'Age must be a number',
    'Age': 'Age',
    'Select your Sex': 'Select your Sex',
    'Sex': 'Sex',
    'Male': 'Male',
    'Female': 'Female',
    'Location is required!': 'Location is required!',
    'Has to be at least 4 letters': 'Has to be at least 4 letters',
    'location': 'location',
    'Submit': 'Submit',
    'Your Name': 'Your Name',
    'Has to be at least 3 letters': 'Has to be at least 3 letters',
    'Illegal characters!': 'Illegal characters!',
    'First Name': 'First Name',
    'Middle Name': 'Middle Name',
    'Last name is required!': 'Last name is required!',
    'Last Name': 'Last Name',
    'Phone number is required!': 'Phone number is required!',
    'Please provide you Phone number': 'Please provide you Phone number',
    'Please provide you complete Phone number':
        'Please provide you complete Phone number',
    "Incorrect give a valid phone number":
        "Incorrect give a valid phone number",
    'Please complete your phone number': 'Please complete your phone number',
    'You have longer phone number or start with "09"':
        'You have longer phone number or start with "09"',
    'Please give the right phone number': 'Please give the right phone number',
    "Contact us": "Contact us",
    "Rate us": "Rate us",
    "Privacy Policy": "Privacy Policy",
    "Terms & Conditions": "Terms & Conditions",
    "Transactions": "Transactions",
    "Alen is created and Owned  by alen call center and mobile application, and developed by Qemer software technology":
        "Alen is created and Owned  by alen call center and mobile application and developed by Qemer software technology",
    "Call us": "Call us",
    "Telegram": "Telegram",
    "Office": "Office",
    "Search by prescription?": "Search by prescription?",
    "Add image of your prescription from your Gallery":
        "Add image of your prescription from your Gallery",
    "Add": "Add",
    "No Health Articles Available": "No Health Articles Available",
    "No Main Ads Available": "No Main Ads Available",
    "No small Ads Available": "No small Ads Available",
    "Ordered by : ": "Ordered by : ",
    'to your cart?': 'to your cart?',
    "How much would you want?": "How much would you want?",
    'Amount': 'Amount',
    'Amount in number': 'Amount in number',
  },
  'am': {
    'Alen': 'አለን',
    'Language': 'ቋንቋ',
    'Services': 'አገልግሎቶች',
    'Pharmacies': 'መድሃኒት ቤት',
    'Imaging': 'የራጅ ምርመራዎች',
    'Labs': 'ላብራቶሪዎች',
    'HomeCare': 'የቤት ውስጥ እንክብካቤ',
    'Health Facilities': 'ሆስፒታሎች',
    'Importers': 'አስመጪዎች',
    'Companies': 'ኩባንያዎች',
    'EmergencyMS': 'ድንገተኛ አደጋ',
    'Trending': 'በመታየት ላይ ያለ',
    'Health Articles': 'የጤና ጽሑፎች',
    'Search': 'ፈልግ',
    'Top Pharmacies': 'ተመራጭ መድሃኒት ቤት',
    'Nearby Pharmacies': 'በአቅራቢያ ያሉ መድሃኒት ቤት',
    'Top Diagnostics': 'ተመራጭ ምርመራ ሰጪዎች',
    'Nearby Diagnostics': 'በአቅራቢያ ያሉ ምርመራ ሰጪዎች',
    'Top Laboratories': 'ተመራጭ ላብራቶሪዎች',
    'Nearby Laboratories': 'በአቅራቢያ ያሉ ላብራቶሪዎች',
    'Top Home Cares': 'ተመራጭ የቤት ውስጥ እንክብካቤዎች',
    'Nearby Home Cares': 'በአቅራቢያ ያሉ የቤት ውስጥ እንክብካቤዎች',
    'Top Hospitals': 'ተመራጭ ሆስፒታሎች',
    'Nearby Hospitals': 'በአቅራቢያ ያሉ ሆስፒታሎች',
    'Top Importers': 'ተመራጭ አስመጪዎች',
    'Nearby Importers': 'በአቅራቢያ ያሉ አስመጪዎች',
    'Top Companies': 'ተመራጭ ኩባንያዎች',
    'Nearby Companies': 'በአቅራቢያ ያሉ ኩባንያዎች',
    'Categories': 'ምድቦች',
    'Office Hours': 'የቢሮ ሰዓቶች',
    'Phone Number': 'ስልክ ቁጥር',
    'Email': 'ኢሜይል',
    'Our Location': 'የእኛ ቦታ',
    'Add to Cart': 'ወደ ቅርጫት ጨምር',
    'Dosage': 'የመድኃኒት መጠን',
    'Made-in': 'የተስራ',
    'Quantity': 'ብዛት',
    'Root': 'ሥር',
    'Price': 'ዋጋ',
    'Yes': 'አዎ',
    'No': 'አይ',
    'Catalogues': 'ካታሎጎች',
    'Sub-catalogue': 'ንዑስ-ካታሎግ',
    'Search by Prescription': 'በሃኪም ማዘዣ ይፈልጉ',
    'Add Prescription': 'የሃኪም ማዘዣዎን በምስል ያስገቡ',
    'Types': 'አይነት',
    'Search Everything': 'ሁሉንም ፈልግ',
    'Confirmation Code is required!': 'የማረጋገጫ ኮድ ያስፈልጋል!',
    'Please provide your Confirmation Code': 'እባክዎ የማረጋገጫ ኮድ ያቅርቡ',
    'Please provide your complete Confirmation Code':
        'እባክዎ የተሟላ የማረጋገጫ ኮድ ያቅርቡ',
    'Incorrect give a valid Confirmation Code':
        'ትክክል አይደለም፣ የሚሰራ የማረጋገጫ ኮድ ይስጡ',
    'Confirmation Code': 'ማረጋግጫ ኮድ',
    'Sign Up': 'ክፈት',
    'Additional Info': 'ተጨማሪ መረጃ',
    'First name is required!': 'የመጀመሪያ ስም ያስፈልጋል!',
    'Incorrect Email Address': 'የተሳሳተ የኢሜል አድራሻ',
    'Age is required!': 'እድሜ ያስፈልጋል!',
    'Please provide you age': 'እባክዎ እድሜዎን ያቅርቡ',
    'Age must be a number': 'ዕድሜ ቁጥር መሆን አለበት',
    'Age': 'ዕድሜ',
    'Select your Sex': 'ጾታዎን ይምረጡ',
    'Sex': 'ጾታ',
    'Male': 'ወንድ',
    'Female': 'ሴት',
    'Location is required!': 'ቦታ ያስፈልጋል!',
    'Has to be at least 4 letters': 'ቢያንስ 4 ፊደላት መሆን አለበት',
    'location': 'አካባቢ',
    'Submit': 'አስገባ',
    'Your Name': 'የአንተ ስም',
    'Has to be at least 3 letters': 'ቢያንስ 3 ፊደላት መሆን አለበት',
    'Illegal characters!': 'ህገወጥ ምልክቶች!',
    'First Name': 'የመጀመሪያ ስም',
    'Middle Name': 'የአባት ስም',
    'Last name is required!': 'የአያት ስም ያስፈልጋል!',
    'Last Name': 'ያባት ስም',
    'Phone number is required!': 'ስልክ ቁጥር ያስፈልጋል!',
    'Please provide you Phone number': 'እባክዎን ስልክ ቁጥር ያቅርቡ',
    'Please provide you complete Phone number': 'እባክዎን ሙሉ ስልክ ቁጥር ያቅርቡ',
    "Incorrect give a valid phone number": "ትክክል አይደለም፣ ትክክለኛ ስልክ ቁጥር ይስጡ",
    'Please complete your phone number': 'እባክዎን ስልክ ቁጥርዎን ይሙሉ',
    'You have longer phone number or start with "09"':
        'ረዘም ያለ ስልክ ቁጥር አለዎት ወይም በ "09" ይጀምሩ',
    'Please give the right phone number': 'እባክዎ ትክክለኛውን ስልክ ቁጥር ይስጡ',
    "Contact us": "አግኙን",
    "Rate us": "ደረጃ ይስጡን",
    "Privacy Policy": "የግላዊነት ፖሊሲ",
    "Terms & Conditions": "ውሎች እና ሁኔታዎች",
    "Transactions": "ግብይቶች",
    "Alen is created and Owned  by alen call center and mobile application, and developed by Qemer software technology":
        "አለን የጤና መረጃ ማእከል ባለቤትነቱ የሂሶፕ ፍርማ ትሬዲንግ ሃ/የተ/የግል ማህበር ሲሆን የተሰራውም በቀመር ሶፍትዌር ቴክኖሎጂ ሃ/የተ/የግል ማህበር ተዘጋጅቶ የቀረበ ነው::",
    "Call us": "ይደውሉልን",
    "Telegram": "ቴሌግራም",
    "Office": "ቢሮ",
    "Search by prescription?": "በሐኪም ትእዛዝ ይፈልጉ?",
    "Add image of your prescription from your Gallery":
        "የሐኪም ማዘዣዎን ምስል ከጋለሪዎ ያክሉ",
    "Add": "ያክሉ",
    "No Health Articles Available": "ምንም የጤና መጣጥፎች የሉም",
    "No Main Ads Available": "ምንም ዋና ማስታወቂያዎች የሉም",
    "No small Ads Available": "ምንም ትናንሽ ማስታወቂያዎች አይገኙም።",
    "Ordered by : ": "የታዘዘው በ : ",
    'to your cart?': 'ወደ ቅርጫትዎ ይጨምሩ',
    "How much would you want?": "ምን ያህል ይፈልጋሉ?",
    'Amount': 'መጠን',
    'Amount in number': 'መጠን በቁጥር',
  },
  'or': {},
  'tg': {},
};

// Add a string called 'languageOption' in your provider and use the following format: 
// lang[languageOption]!['Amount']!